name: Clean reports when issues/PR are closed

on:
  schedule:
    - cron: '30 3 * * 3'
  workflow_dispatch:
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout strudy
      uses: actions/checkout@v4
      with:
        path: strudy
    - name: Checkout webref
      uses: actions/checkout@v4
      with:
        repository: w3c/webref
        path: webref
    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      working-directory: strudy
      run: |
        npm ci

    - name: Drop reports locally when related issues/PR are closed
      working-directory: strudy
      run: node src/reporting/clean-reports.js ../webref/ed/
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create PR to drop reports from repo if needed
      uses: peter-evans/create-pull-request@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: Drop no longer relevant reports
        commit-message: "Drop no longer relevant reports"
        body: ${{ env.dropped_reports }}
        path: strudy
        assignees: tidoust, dontcallmedom
        branch: clean-reports
        branch-suffix: timestamp
