name: Clean reports when issues/PR are closed

on:
  schedule:
    - cron: '30 3 * * 3'
  workflow_dispatch:
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout strudy
      uses: actions/checkout@v2

    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Drop reports locally when related issues/PR are closed
      run: node tools/clean-reports.js
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create PR to drop reports from repo if needed
      uses: peter-evans/create-pull-request@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: Drop reports whose related issues have been closed
        commit-message: "Drop reports whose related issues have been closed"
        body: ${{ env.dropped_reports }}
        assignees: tidoust, dontcallmedom
        branch: clean-reports
        branch-suffix: timestamp
