on:
  workflow_dispatch:

name: Submit draft issue reports from Strudy analysis
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Checkout strudy
      uses: actions/checkout@v4
      with:
        path: strudy
    - name: Install dependencies
      run: npm ci
      working-directory: strudy
    - name: Checkout webref
      uses: actions/checkout@v4
      with:
        repository: w3c/webref
        path: webref
    - name: Configure git
      run: |
        git config user.name "strudy-bot"
        git config user.email "<>"
        git remote set-url --push origin https://x-access-token:${{ secrets.ISSUE_REPORT_GH_TOKEN }}@github.com/$GITHUB_REPOSITORY
      working-directory: strudy
    - name: Run Strudy to detect new anomalies
      working-directory: strudy
      run: node strudy.js inspect ../webref --issues issues --what brokenLinks discontinuedReferences --update-mode old
    - name: Run issue filer script
      working-directory: strudy
      run: node src/reporting/file-issue-for-review.js --max 10
      env:
        GITHUB_TOKEN: ${{ secrets.ISSUE_REPORT_GH_TOKEN }}


