on:
  workflow_dispatch:

name: Submit draft issue reports from Strudy analysis
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Checkout strudy
      uses: actions/checkout@v2
      with:
        path: strudy
    - name: Install dependencies
      run: npm ci
      working-directory: strudy
    - name: Checkout webref
      uses: actions/checkout@v2
      with:
        repository: w3c/webref
        path: webref
    - name: Configure git
      run: |
        git config user.name "strudy-bot"
        git config user.email "<>"
        git remote set-url --push origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      working-directory: strudy
    - name: Run issue filer script
      working-directory: strudy
      run: node src/reporting/file-issue-for-review.js ../webref/ed/ ../webref/tr/ brokenLinks
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


