on:
  workflow_dispatch:

name: Submit issue from Strudy analysis to relevant github repo
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Checkout strudy
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Configure git
      run: |
        git config user.name "strudy-bot"
        git config user.email "<>"
        git remote set-url --push origin https://x-access-token:${{ secrets.ISSUE_REPORT_GH_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: Run issue submitter script
      run: node src/reporting/submit-issue.js
      env:
        GH_TOKEN: ${{ secrets.ISSUE_REPORT_GH_TOKEN }}


