on:
  workflow_dispatch:
    inputs:
      path:
        description: 'path of the report to submit (relative to issues/)'
        required: true

name: Submit issue from Strudy analysis to relevant github repo
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Checkout strudy
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Configure git
      run: |
        git config user.name "strudy-bot"
        git config user.email "<>"
        git remote set-url --push origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: Run issue submitter script
      run: node src/reporting/submit-issue.js issues/{{ github.event.inputs.path }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


